Pr badge max length
varletjs/varlet pull request #883
Opened 2023-03-07 15:35 UTC by dyggod

## Checklist

---

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information
badge组件提供字符最大长度属性
---

2023-03-07 16:59 UTC, haoziqaq commented
个人感觉这里使用限制字符数量来解决文本过长的问题不是很合适。中英文、数字、符号显示的尺寸不一致，用户可能期望看到相同尺寸的徽标，而不是相同字符的徽标。个人认为这边增加一个 `value` 插槽并使用我们的 `Ellipsis` + `value` 插槽，来解决会更加合适。

2023-03-07 23:33 UTC, dyggod commented
> 

你说得对，今晚我调整下。

2023-03-08 10:15 UTC, nonzzz requested changes

2023-03-08 10:15 UTC, nonzzz commented on packages/varlet-ui/src/badge/Badge.vue
> +      if (value !== undefined && maxLength > 0 && typeof value === 'string' && value.length > maxLength) {
`typeof value === 'string'` is  necessary? According the `props.ts` file. we can know the value 
can be number or string. So if we limited with `string`. User may despair that why i input `<var-badge :value="remoteValue"  max-length="5"/>` can't work : (

2023-03-08 15:35 UTC, dyggod commented on packages/varlet-ui/src/badge/Badge.vue
> +      if (value !== undefined && maxLength > 0 && typeof value === 'string' && value.length > maxLength) {
你说的对，确实没必要，其实这是我自己的假想需求，我觉得可能要通过限制用户的行为或者说使用来提供这个功能，其实不应该这样。现在已经改为使用ellispsis组件来实现。

2023-03-08 15:39 UTC, nonzzz approved these changes

2023-03-08 18:14 UTC, haoziqaq commented
可能是我没有表达清楚，我想我们应该没办法通过字符数量去解决固定尺寸的问题，因为在实际的业务需求和设计图中一般会要求徽标的尺寸一致而不是字数一致。我们只需要给 `value` 提供个插槽就可以了，样式之类的东西交给用户去处理。期望的使用方式如下。

```html
<var-badge position="right-top">
  <var-avatar src="https://varlet.gitee.io/varlet-ui/cat.jpg" />

  <template #value>
    <var-ellipsis style="max-width: 80px">20000000000</var-ellipsis>
  </template>
</var-badge>
```

2023-03-08 18:23 UTC, haoziqaq commented
方便的话，顺便移除 badge 在四个角定位时的边框。这是一个错误的设计。

2023-03-08 23:48 UTC, dyggod commented
> 可能是我没有表达清楚，我想我们应该没办法通过字符数量去解决固定尺寸的问题，因为在实际的业务需求和设计图中一般会要求徽标的尺寸一致而不是字数一致。我们只需要给 `value` 提供个插槽就可以了，样式之类的东西交给用户去处理。期望的使用方式如下。
> 
> ```
> <var-badge position="right-top">
>   <var-avatar src="https://varlet.gitee.io/varlet-ui/cat.jpg" />
> 
>   <template #value>
>     <var-ellipsis style="max-width: 80px">20000000000</var-ellipsis>
>   </template>
> </var-badge>
> ```

啊抱歉，早上的评论晚上改的时候就给忘了，我的锅

2023-03-09 14:13 UTC, dyggod commented
please review again @haoziqaq

2023-03-09 14:28 UTC, merged